name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build with Maven
        run: mvn clean install

      - name: Run tests
        run: mvn test

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PAT }}

      - name: Build and push Docker images
        run: docker-compose build

      - name: Start Docker Compose services
        run: docker-compose up -d

      - name: Wait for MSSQL to be ready
        run: |
          until docker exec -it mssql /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P YourStrong!Password123 -Q 'SELECT 1'; do
            echo "Waiting for MSSQL to be ready..."
            sleep 15
          done

      - name: Run tests
        run: docker exec url-shortener mvn test

      - name: Tear down Docker Compose services
        if: always()
        run: docker-compose down